import Navbar from '@/components/Navbar';
import Banner from '@/components/Banner';
import About from '@/components/About';

import Head from 'next/head'
import {motion} from 'framer-motion'
import Projects from '@/components/Projects';

import Contact from '@/components/Contact';
import Footer from '@/components/Footer'

// variants
import {fadeIn} from '../variants'




export default function Home() {
  return (
    <>
      <Head>
        <title>Felix Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.ico" />
      </Head>
      <main className="w-full h-screen font-bodyFont bg-bodyColor
       text-textLight overflow-x-hidden overflow-y-scroll scrollbar
       scrollbar-track-textDark/20 scrollbar-thumb-textDark/60">
       <Navbar/>
       <div className="w-full h-[88vh] xl:flex items-center gap-20 justify-between">
        <motion.div 
         variants={fadeIn('up', 0.4)}
         initial="hidden"
         animate="show"
         exit="hidden"
         className="hidden xl:inline-flex w-32 h-full fixed left-0 bottom-0">
        
        </motion.div >
        <div className="h-[88vh] w-full mx-auto p-4">
        <Banner />
        <About />
        <Projects />
        <Contact />
        <Footer />
        </div>
        <motion.div 
          variants={fadeIn('down', 0.6)}
          initial="hidden"
          animate="show"
          exit="hidden"
        className="hidden xl:inline-flex w-32 h-full fixed right-0 bottom-0">
        </motion.div>
       </div>
      </main>
    </>
  );
};
