import Navbar from '@/components/Navbar';
import Banner from '@/components/Banner';
import Head from 'next/head'
import {motion} from 'framer-motion'
import { online } from "@/public/assets";
import Image from "next/image";


// variants
import {fadeIn} from '../variants'





export default function Home() {
  return (
    <>
      <Head>
        <title>Felix Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.icon" />
      </Head>
      <main className="w-full mdl:h-[100vh] xl:h-screen font-bodyFont bg-bodyColor relative
       text-textLight overflow-x-hidden overflow-y-scroll scrollbar
       scrollbar-track-textDark/20 scrollbar-thumb-textDark/60">
       
       
       <Navbar/>
        <div className="w-full relative overflow-hidden">
        <Banner />
        </div>
        <div className='py-6 mt-[1rem] relative overflow-hidden'>
        <div className="flex justify-center items-center gap-4">
          <Image src={online} alt="online" 
          className="w-[8px] mb-1"/> 
          <h4 className="font-titleFont text-textDark font-semibold">Available for work</h4>
        </div>
        </div>
       
        
      </main>
    </>
  );
};