import Navbar from '@/components/Navbar';
import Banner from '@/components/Banner';
import Head from 'next/head'
import {motion} from 'framer-motion'


// variants
import {fadeIn} from '../variants'





export default function Home() {
  return (
    <>
      <Head>
        <title>Felix Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.ico" />
      </Head>
      <main className="w-full bottom-0 font-bodyFont bg-bodyColor relative
       text-textLight overflow-x-hidden overflow-y-scroll scrollbar
       scrollbar-track-textDark/20 scrollbar-thumb-textDark/60">
       
       
       <Navbar/>
        <div className="w-full overflow-hidden">
        <Banner />
        

</div>
        
      </main>
    </>
  );
};
